services:
  db:
    container_name: db
    build:
      context: ./SERVICES/db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=main
    volumes:
      - db_data:/var/lib/postgresql/data

  # back:
  #   container_name: back
  #   build:
  #     context: .
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/main
  #     - SPRING_DATASOURCE_USERNAME=admin
  #     - SPRING_DATASOURCE_PASSWORD=123456
  #   depends_on:
  #     - db
  #   volumes:
  #     - ./src:/app/src # Mount source for hot reload

volumes:
  db_data:
    driver: local
