services:
  db:
    build:
      context: ./SERVICES/db
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=main
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  # Spring Boot app service for development
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - db
  #   environment:
  #     - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/main
  #     - SPRING_DATASOURCE_USERNAME=admin
  #     - SPRING_DATASOURCE_PASSWORD=123456

volumes:
  db_data:
    driver: local
